// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package storage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIPurchaseDAO is an autogenerated mock type for the IPurchaseDAO type
type MockIPurchaseDAO struct {
	mock.Mock
}

// Purchase provides a mock function with given fields: ctx, updatedWager, buyingPrice
func (_m *MockIPurchaseDAO) Purchase(ctx context.Context, updatedWager *Wager, buyingPrice float64) (*Purchase, error) {
	ret := _m.Called(ctx, updatedWager, buyingPrice)

	var r0 *Purchase
	if rf, ok := ret.Get(0).(func(context.Context, *Wager, float64) *Purchase); ok {
		r0 = rf(ctx, updatedWager, buyingPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Purchase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Wager, float64) error); ok {
		r1 = rf(ctx, updatedWager, buyingPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
